version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_3110Project
  gitServerName: rimaSC
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.siqa_gittest_3110.integrations:Call_TPPService
  packages:
  - name: SIQA_GITTEST_3110Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2092
- serviceName: project.siqa_gittest_3110.integrations:Test_ConnList
  packages:
  - name: SIQA_GITTEST_3110Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_gittest_3110.integrations:Test_RestConnector
  packages:
  - name: SIQA_GITTEST_3110Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.spyenabled: "false"
  jdbc.SAP TxStore Pool.minConns: "5"
  jdbc.SAP TxStore Pool.userid: root
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.SAP TxStore Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
